  GNU nano 7.2                                       docker-compose.yaml                                                version: '3.8'

services:
  crypto-alerts:
    image: ghcr.io/angility/coin_checker:latest
    container_name: crypto-alerts-bot
    restart: unless-stopped
    volumes:
      - ./config/conf.yaml:/app/config/conf.yaml:ro
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Novosibirsk
    networks:
      - crypto-net

networks:
  crypto-net:
    driver: bridge